Add pagination, sorting, and Swagger documentation to existing contro…
misterSokor/litflix-app pull request #3
Opened 2024-09-27 02:11 UTC by misterSokor

…llers

2024-09-27 12:38 UTC, Elena-Bruyako requested changes
see comments

2024-09-27 12:38 UTC, Elena-Bruyako commented on pom.xml
> +        <!-- SWAGGER DEPENDENCIES -->
remove comment

2024-09-27 12:38 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/repository/book/BookRepository.java
> +        JpaSpecificationExecutor<Book>, PagingAndSortingRepository<Book, Long> {
```suggestion
        JpaSpecificationExecutor<Book> {
```

2024-10-01 12:34 UTC, Elena-Bruyako requested changes
You provide pageable to endpoints, but don't use it in service.

2024-10-01 12:34 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/controller/BookController.java
>                                       @RequestParam(required = false) String[] author) {
add Pageable

2024-10-01 12:34 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/controller/BookController.java
>          BookSearchParametersDto bookSearchParametersDto =
add `@Valid` to updateBook endpoint

2024-10-04 17:13 UTC, misterSokor commented on src/main/java/com/store/litflix/controller/BookController.java
>                                       @RequestParam(required = false) String[] author) {
Thank you!

2024-10-05 08:05 UTC, okuzan approved these changes

2025-01-08 19:21 UTC, merged